version: '3.7'

volumes:
  farmlab-db-data:
  farmlab-db-conf:

services:
  landing:
    image: httpd:alpine
    container_name: "farmlab-landing"
    restart: unless-stopped
    volumes:
      - ./landing:/usr/local/apache2/htdocs/.
    networks:
      - traefik_proxy
    labels:
      - "traefik.backend=FarmLabLandingServer"
      - "traefik.frontend.rule=Host:farmlab.team"
      - "traefik.docker.network=management_proxy-bridge"
      - "traefik.port=80"
  api:
    build: ./api
    container_name: "farmlab-api"
    restart: unless-stopped
    networks:
      - traefik_proxy
      - internal
    ports:
      - 1883:1883
    depends_on:
      - database
    labels:
      - "traefik.backend=FarmLabAPI"
      - "traefik.frontend.rule=Host:api.farmlab.team"
      - "traefik.docker.network=management_proxy-bridge"
      - "traefik.port=5000"
  cloud:
    build: ./cloud
    container_name: "farmlab-cloud"
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.backend=FarmLabCloud"
      - "traefik.frontend.rule=Host:cloud.farmlab.team"
      - "traefik.docker.network=management_proxy-bridge"
      - "traefik.port=4200"
  database:
    image: 'mongo'
    container_name: "farmlab-db"
    restart: unless-stopped
    networks: 
      - internal
    volumes:
      - farmlab-db-data:/data/db
      - farmlab-db-conf:/data/configdb
    labels:
      - "traefik.backend=FarmLabDatabase"
      - "traefik.enable=false"

networks:
  internal:
  traefik_proxy:
    external:
      name: management_proxy-bridge