version: '3'

volumes:
  farmlab-db-data:
  farmlab-db-conf:

services:
  api:
    build: ./api
    container_name: "farmlab-api"
    restart: unless-stopped
    networks:
      - internal
      # - traefik_proxy
    ports:
      - 3000:3000
    labels:
      - "traefik.backend=FarmLabAPI"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api.farmlab.team"
      - "traefik.port=3000"
  mqtt:
    build: ./mqtt
    container_name: "farmlab-mqtt-broker"
    restart: unless-stopped
    networks:
      - internal
      # - traefik_proxy
    ports:
      - 1883:1883
    labels:
      - "traefik.backend=FarmLabMQTT"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:mqtt.farmlab.team"
      - "traefik.port=1883"
  database:
    image: 'mongo'
    container_name: "farmlab-db"
    restart: unless-stopped
    volumes:
      - farmlab-db-data:/data/db
      - farmlab-db-conf:/data/configdb
    networks:
      - internal
    labels:
      - "traefik.backend=FarmLabDatabase"
      - "traefik.enable=false"

networks:
  internal:
    driver: bridge
  # traefik_proxy:
  #   external:
  #     name: management_proxy-bridge