version: '3.0' 
 
services:
 angular: 
  build: frontend
  restart: always
  ports:
    - "4200:4200"
 
 express: 
  build: backend
  restart: always
  ports:
    - "3000:3000" 
  links:
    - db
 db:
    image: postgres:latest
    environment: 
      - "POSTGRES_PASSWORD: example"
    restart: always
    ports:
      - "5432:5432" # postgres binding to a non docker network
    volumes: 
      - ./volume:/var/lib/postgresql/data