version: '3.0' 
 
services:
 angular: 
  build: frontend
  restart: always
  ports:
    - "4200:4200"
 
 express: 
  build: backend
  restart: always
  ports:
    - "3000:3000" 
  links:
    - db:database

 db: 
  build: database
  restart: always
  ports:
    - "5432:5432"